### ISSUE TITLE
Melhorar SEO p/ Google

### ISSUE THREAD

**Issue by cmdalbem** [cmdalbem/bikedeboa#32]
O crawler do Google está devidamente reconhecendo as diferentes páginas do site, mas não está carregando corretamente as metatags, como título e descrição.
Esse problema pode ser constatado fazendo uma busca filtrada por domínio: https://www.google.com.br/?q=site:www.bikedeboa.com.br
Além disso podemos fazer outras coisas pra melhorar o SEO dos bicicletários

- [X] mandar sitemap inicial pro Google Search Console
- [x] microformatos

**Comment by tsaldanha** [comment]
Vou estudar melhor como renderizar as tags em um SPA como o bikedeboa, algumas paginas retornam o conteúdo
![screen shot 2017-12-24 at 14 33 56](https://user-images.githubusercontent.com/218050/34327893-bc0f54f6-e8b7-11e7-80b1-10b04bf6f35a.png)
 corretamente.

**Comment by cmdalbem** [comment]
O segredo tá na funcao setPageTitle(), onde eu dinamicamente seto as metatags da pagina com os detalhes do bicicletário aberta. Acho que é só adicionar lá a lógica pra preencher os microformatos.
O fato de alguns resultados do Google estarem corretos e outros não é só porque eu fui melhorando isso ao longo do tempo, e o crawler não atualiza muito frequentemente.
